#############################################################################
# Makefile for building: mapIt.app/Contents/MacOS/mapIt
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  mapIt.pro
# Template: app
# Command: /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile mapIt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineCore.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQuick.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQml.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtPositioning.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang -F/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib
QMAKE         = /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mapIt1.0.0
DISTDIR = /Users/vunguyen/Dropbox/Spring\ 2018/CS\ 8/tests/Shortest\ Path/.tmp/mapIt1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib -framework QtWebEngineWidgets -framework QtWebEngineCore -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWebChannel -framework QtPositioning -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		graph.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		graph.o \
		moc_mainwindow.o
DIST          = /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qdevice.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/device_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/unix.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/macx.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qconfig.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_post.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resources.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/moc.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/uic.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/yacc.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/lex.prf \
		mapIt.pro mainwindow.h \
		data.h \
		graph.h main.cpp \
		mainwindow.cpp \
		graph.cpp
QMAKE_TARGET  = mapIt
DESTDIR       = 
TARGET        = mapIt.app/Contents/MacOS/mapIt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d mapIt.app/Contents/MacOS/ || mkdir -p mapIt.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mapIt.pro /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qdevice.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/device_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/unix.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/macx.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qconfig.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_post.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resources.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/moc.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/uic.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/yacc.prf \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/lex.prf \
		mapIt.pro \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/QtWebEngineWidgets.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineCore.framework/QtWebEngineCore.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/QtWebChannel.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtPositioning.framework/QtPositioning.prl \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile mapIt.pro
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qdevice.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/device_config.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/unix.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/mac.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/macx.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/sanitize.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/qconfig.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt_config.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_pre.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/default_post.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qml_debug.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/warn_on.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/qt.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/resources.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/moc.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/opengl.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/uic.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/file_copies.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/exceptions.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/yacc.prf:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/features/lex.prf:
mapIt.pro:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/QtWebEngineWidgets.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineCore.framework/QtWebEngineCore.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/QtWebChannel.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtPositioning.framework/QtPositioning.prl:
/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile mapIt.pro

qmake_all: FORCE

mapIt.app/Contents/PkgInfo: 
	@test -d mapIt.app/Contents || mkdir -p mapIt.app/Contents
	@$(DEL_FILE) mapIt.app/Contents/PkgInfo
	@echo "APPL????" > mapIt.app/Contents/PkgInfo
mapIt.app/Contents/Resources/empty.lproj: 
	@test -d mapIt.app/Contents/Resources || mkdir -p mapIt.app/Contents/Resources
	@touch mapIt.app/Contents/Resources/empty.lproj
	
mapIt.app/Contents/Info.plist: 
	@test -d mapIt.app/Contents || mkdir -p mapIt.app/Contents
	@$(DEL_FILE) mapIt.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,VuNguyen.mapIt,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,mapIt,g" -e "s,@LIBRARY@,mapIt,g" -e "s,@TYPEINFO@,????,g" /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang/Info.plist.app >mapIt.app/Contents/Info.plist

all: Makefile \
		mapIt.app/Contents/PkgInfo \
		mapIt.app/Contents/Resources/empty.lproj \
		mapIt.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h data.h graph.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp graph.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mapIt.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEngineView \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebengineview.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/QWebChannel \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/qwebchannel.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QDir \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qdir.h \
		graph.h \
		data.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEnginePage \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebenginepage.h \
		mainwindow.h
	/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/mkspecs/macx-clang -I'/Users/vunguyen/Dropbox/Spring 2018/CS 8/tests/Shortest Path' -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineCore.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQuick.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtQml.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtPositioning.framework/Headers -I/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEngineView \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebengineview.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/QWebChannel \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/qwebchannel.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QDir \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qdir.h \
		graph.h \
		data.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEnginePage \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebenginepage.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEngineView \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebengineview.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/QWebChannel \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebChannel.framework/Headers/qwebchannel.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QDir \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qdir.h \
		graph.h \
		data.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEnginePage \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebenginepage.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

graph.o: graph.cpp graph.h \
		data.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/QWebEnginePage \
		/Users/vunguyen/Qt5.6.30/5.6.3/clang_64/lib/QtWebEngineWidgets.framework/Headers/qwebenginepage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

